### ISSUE TITLE
Office365 autodiscover only works for Exchange2007_SP1

### ISSUE THREAD

**Issue by dconnelly** [OfficeDev/ews-java-api#459] opened 2015-11-15 21:35 UTC
The following code works correctly:

```java
public static void main(String... args) throws Exception {
  ExchangeVersion autodiscoverVersion = ExchangeVersion.Exchange2007_SP1;
  ExchangeService es = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
  es.setTraceEnabled(true);
  es.setTraceFlags(EnumSet.allOf(TraceFlags.class));
  es.setTraceListener((type, message) -> System.out.println("[" + type + "] " + message));
  es.setCredentials(new WebCredentials("dac.test@pexlabs.onmicrosoft.com", PASSWORD));
  AutodiscoverService as = new AutodiscoverService(es, autodiscoverVersion);
  as.setRedirectionUrlValidationCallback(redirectionUrl -> true);
  as.setWebProxy(es.getWebProxy());
  as.setEnableScpLookup(true);
  GetUserSettingsResponse response = as.getUserSettings("dac.test@pexlabs.onmicrosoft.com", UserSettingName.UserDisplayName);
  System.out.println("XXX settings = " + response.getSettings());
}
```

However if I change `autodiscoverVersion` to `ExchangeVersion.Exchange2010_SP2` the code fails with the following error:
```
[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:28Z">
Determining which endpoints are enabled for host pexlabs.onmicrosoft.com
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:28Z">
No Autodiscover endpoints are available for host pexlabs.onmicrosoft.com
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:28Z">
Determining which endpoints are enabled for host autodiscover.pexlabs.onmicrosoft.com
</Trace>

2015-11-15 13:25:29,668 INFO org.apache.http.impl.execchain.RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443: No route to host
2015-11-15 13:25:29,674 INFO org.apache.http.impl.execchain.RetryExec: Retrying request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443
2015-11-15 13:25:30,955 INFO org.apache.http.impl.execchain.RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443: No route to host
2015-11-15 13:25:30,955 INFO org.apache.http.impl.execchain.RetryExec: Retrying request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443
2015-11-15 13:25:31,842 INFO org.apache.http.impl.execchain.RetryExec: I/O exception (java.net.NoRouteToHostException) caught when processing request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443: No route to host
2015-11-15 13:25:31,843 INFO org.apache.http.impl.execchain.RetryExec: Retrying request to {s}->https://autodiscover.pexlabs.onmicrosoft.com:443
[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:32Z">
No Autodiscover endpoints are available for host autodiscover.pexlabs.onmicrosoft.com
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:32Z">
Trying to get Autodiscover redirection URL from http://autodiscover.pexlabs.onmicrosoft.com/autodiscover/autodiscover.xml.
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:33Z">
Redirection URL found: 'https://autodiscover-s.outlook.com/autodiscover/autodiscover.xml'
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:33Z">
Determining which endpoints are enabled for host autodiscover-s.outlook.com
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:33Z">
Host returned enabled endpoint flags: [Legacy]
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:33Z">
No Autodiscover endpoints are available  for host autodiscover-s.outlook.com
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:33Z">
Trying to get Autodiscover host from DNS SRV record for pexlabs.onmicrosoft.com.
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:34Z">
DnsQuery returned error 'DNS name not found [response code 3]'.
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:34Z">
No appropriate SRV record was found.
</Trace>

[AutodiscoverConfiguration] <Trace Tag="AutodiscoverConfiguration" Tid="1" Time="2015-11-15 21:25:34Z">
No matching Autodiscover DNS SRV records were found.
</Trace>


microsoft.exchange.webservices.data.autodiscover.exception.AutodiscoverLocalException: The Autodiscover service couldn't be located.

	at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getSettings(AutodiscoverService.java:1196)
	at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1043)
	at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.internalGetSoapUserSettings(AutodiscoverService.java:987)
	at microsoft.exchange.webservices.data.autodiscover.AutodiscoverService.getUserSettings(AutodiscoverService.java:1849)
    ...
```
Is this expected behavior or the auto discover process somewhat broken for Office365?

**Comment by avromf** [comment] 2015-11-16 14:51
I'm wondering whether this is a possible duplicate of #452 ?

**Comment by dconnelly** [comment] 2015-11-16 22:57
Definitely a duplicate of #452

**Closed** 2015-11-16 22:57 UTC
