### ISSUE TITLE
Events that are "all day" show up in CalendarFolder.findAppointments() on next day

### ISSUE THREAD

**Issue by thomasehardt** [OfficeDev/ews-java-api#350] opened 2015-06-15 18:21 UTC
For example, I create an all day event for 2015-07-01 and call it "July 1st". If I look for appointments on 2015-07-02, that event shows up.

From what I can see, the all day event is defined as starting at 2015-07-01 00:00 and ending at 2015-07-02 00:00, and ````isAllDay()```` returns true for this event.

My expectation is that such an event would only show up for 2015-07-01.

here's the basic call I'm using
````
CalendarFolder folder = CalendarFolder.bind(service, WellKnownFolderName.Calendar);
FindItemsResults<Appointment> results = folder.findAppointments(new CalendarView(start, etnd));
````

Server is 2010 SP2

**Comment by 805728578** [comment] 2015-06-16 02:05
you can do for all day:

CalendarFolder calendar = CalendarFolder.bind(service, WellKnownFolderName.Calendar);
SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
Date startDate = formatter.parse("2015-07-01 00:00:00");
 Date endDate = formatter.parse("2015-07-01 23:59:59");
FindItemsResults<Appointment> appointments = calendar.findAppointments(new CalendarView(startDate, endDate));

**Comment by evpaassen** [comment] 2015-06-16 13:54
Might be a duplicate of #328.

**Comment by thomasehardt** [comment] 2015-06-16 14:29
The suggestion above for all day would still pick up the appointment for 2015-07-02, and the underlying use case here is to display a calendar in a portal - looking up one day at a time would require up to 31 calls to the exchange server instead of just one.

**Comment by thomasehardt** [comment] 2015-06-16 14:33
I'm not sure about this being a duplicate of #328 - it very well may be - I did see that issue and thought it pertained more to time zone differences. That issue, however, was also reported for ````ExchangeVersion.Exchange2010_SP2````

In my case, the ````Appointment```` object does correctly report that the event is an all day event.

For an interim workaround, I'll perform an extra check on events that are all day.

**Closed** 2015-08-15 00:17 UTC
Labels: duplicate
